### ISSUE TITLE
Provide the source code

### ISSUE THREAD

**Issue by menelike** [realwear/HTML#1]
Hi guys,

please provide the source code of this project. This application has bugs which can't be easily tackled down as long as the source code is not provided. This would also help this project to become more stable.

In addition, it would be great to get some background info or a data flow which describes the magic happening behind the curtain. Afaik the XML is recognized by the underlying speech-to-text engine, it would be great to have more knowledge about that (can we update that XML on the fly?). We're trying to use this application in a `react` project, I have a strong feeling that we can skip a lot of the internal event/cleanup logic. One way could be to provide the XML by ourself.

Thanks a lot!

**Comment by lukerealwear** [comment]
Thank you for the feedback.

Source code has been uploaded to Github. The xml added to the web pages is based around WearML. 

http://developer.realwear.com/wearml-scripting

Apologies we are continually update our developer documentation and not everything is present at the moment. If you require more information please do not hesitate to contact support@realwear.com and we will be able to provide more detail into the problems you are facing.
